on: [push]
name: Bicep-Build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main
    
    - name: Bicep Build
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: main.bicep
        outputFilePath: azuredeploy.json
    
    - name: upload json file
      uses: actions/upload-artifact@v2
      with:
        name: azuredeploy.json
        path: azuredeploy.json