on:
  push:
    paths-ignore:
      - "build"
    branches:
      - "main"
  workflow_dispatch:

name: Deploy to Azure
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      #get utc timestamp
      - name: Get UTC timestamp
        id: timestamp
        run: echo "::set-output name=utc::$(date -u +%Y-%m-%dT%H_%M_%S)"

      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: westeurope
          template: ./main.bicep
          deploymentname: Stocktracker.${{ steps.timestamp.outputs.utc }}
          parameters: apiKey=${{ secrets.APIKEY}} repositoryToken=${{ secrets.SWA_REPO_TOKEN }} CLEARBIT_API_KEY=${{ secrets.CLEARBIT_API_KEY }}
